---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-lib-grafana-claim
  namespace: grafana-infra-sit
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: grafana-sc
  resources:
    requests:
      storage: 5Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-grafana-claim
  namespace: grafana-infra-sit
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: grafana-sc
  resources:
    requests:
      storage: 5Gi
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-log-grafana-claim
  namespace: grafana-infra-sit
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: grafana-sc
  resources:
    requests:
      storage: 5Gi
  
