---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-v1-0
  namespace: grafana-infra-sit
data:
  prom.yaml: |
    apiVersion: 1

    datasources:
     - name: Prometheus
       type: prometheus
       access: direct
       orgId: 1
       url: http://prometheus-host:30001
       isDefault: true
       version: 1
       editable: false

